
import { Product, Language } from './types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  uz: {
    home: "Bosh sahifa",
    catalog: "Katalog",
    favorites: "Sevimlilar",
    cart: "Savat",
    compare: "Solishtirish",
    search: "Qidiruv...",
    login: "Kirish",
    register: "Ro'yhatdan o'tish",
    buy: "Sotib olish",
    addToCart: "Savatga qo'shish",
    installments: "Muddatli to'lov",
    description: "Tavsif",
    characteristics: "Xususiyatlari",
    reviews: "Fikrlar",
    color: "Rang",
    size: "O'lcham",
    checkout: "Rasmiylashtirish",
    fullName: "Ism sharif",
    phone: "Telefon raqam",
    sendOrder: "Buyurtma berish",
    adminPanel: "Admin Panel",
    stock: "Omborda",
    new: "Yangi",
    action: "Aksiya",
    discount: "Chegirma",
    promocode: "Promokod",
    apply: "Qo'llash",
    total: "Jami",
    publicOffer: "Ommaviy oferta",
    termsOfUse: "Foydalanish shartlari",
    installmentMonths: "oyga",
    back: "Orqaga"
  },
  ru: {
    home: "Главная",
    catalog: "Каталог",
    favorites: "Избранное",
    cart: "Корзина",
    compare: "Сравнение",
    search: "Поиск...",
    login: "Вход",
    register: "Регистрация",
    buy: "Купить",
    addToCart: "В корзину",
    installments: "Рассрочка",
    description: "Описание",
    characteristics: "Характеристики",
    reviews: "Отзывы",
    color: "Цвет",
    size: "Размер",
    checkout: "Оформление",
    fullName: "Имя и фамилия",
    phone: "Номер телефона",
    sendOrder: "Заказать",
    adminPanel: "Админ Панель",
    stock: "В наличии",
    new: "Новинка",
    action: "Акция",
    discount: "Скидка",
    promocode: "Промокод",
    apply: "Применить",
    total: "Итого",
    publicOffer: "Публичная оферта",
    termsOfUse: "Условия использования",
    installmentMonths: "мес",
    back: "Назад"
  },
  en: {
    home: "Home",
    catalog: "Catalog",
    favorites: "Favorites",
    cart: "Cart",
    compare: "Compare",
    search: "Search...",
    login: "Login",
    register: "Register",
    buy: "Buy Now",
    addToCart: "Add to Cart",
    installments: "Installments",
    description: "Description",
    characteristics: "Specs",
    reviews: "Reviews",
    color: "Color",
    size: "Size",
    checkout: "Checkout",
    fullName: "Full Name",
    phone: "Phone Number",
    sendOrder: "Place Order",
    adminPanel: "Admin Panel",
    stock: "In Stock",
    new: "New",
    action: "Action",
    discount: "Discount",
    promocode: "Promo Code",
    apply: "Apply",
    total: "Total",
    publicOffer: "Public Offer",
    termsOfUse: "Terms of Use",
    installmentMonths: "mo",
    back: "Back"
  }
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: { uz: "iPhone 15 Pro Max", ru: "iPhone 15 Pro Max", en: "iPhone 15 Pro Max" },
    description: {
      uz: "Ajoyib titan korpus va kuchli A17 Pro chipiga ega smartfon.",
      ru: "Смартфон с великолепным титановым корпусом и мощным чипом A17 Pro.",
      en: "Smartphone with a stunning titanium build and the powerful A17 Pro chip."
    },
    price: 12000000,
    oldPrice: 13500000,
    image: "https://picsum.photos/seed/iphone15/400/400",
    category: "Smartphones",
    rating: 4.9,
    reviewsCount: 128,
    stock: 15,
    isAction: true,
    isNew: true,
    colors: ["Titanium Black", "Blue Titanium", "Natural Titanium"],
    sizes: ["128GB", "256GB", "512GB", "1TB"],
    specs: {
      "Display": "6.7-inch OLED",
      "Chip": "A17 Pro",
      "Camera": "48MP Main"
    }
  },
  {
    id: "2",
    name: { uz: "MacBook Air M2", ru: "MacBook Air M2", en: "MacBook Air M2" },
    description: {
      uz: "Yengil va kuchli noutbuk, kun bo'yi ishlaydigan batareya bilan.",
      ru: "Легкий и мощный ноутбук с аккумулятором на весь день.",
      en: "Thin and light laptop with all-day battery life."
    },
    price: 10500000,
    image: "https://picsum.photos/seed/macbook/400/400",
    category: "Laptops",
    rating: 4.8,
    reviewsCount: 85,
    stock: 8,
    isNew: true,
    colors: ["Midnight", "Starlight", "Silver"],
    sizes: ["8GB/256GB", "16GB/512GB"],
    specs: {
      "Display": "13.6-inch Liquid Retina",
      "Chip": "Apple M2",
      "Battery": "Up to 18 hours"
    }
  },
  {
    id: "3",
    name: { uz: "Sony WH-1000XM5", ru: "Sony WH-1000XM5", en: "Sony WH-1000XM5" },
    description: {
      uz: "Sinfidagi eng yaxshi shovqinni pasaytirish tizimi.",
      ru: "Лучшая в своем классе система шумоподавления.",
      en: "Best-in-class noise cancellation headphones."
    },
    price: 3500000,
    oldPrice: 4000000,
    image: "https://picsum.photos/seed/sony/400/400",
    category: "Audio",
    rating: 4.7,
    reviewsCount: 210,
    stock: 25,
    isAction: true,
    colors: ["Black", "Silver"],
    sizes: ["One Size"],
    specs: {
      "Battery": "30 hours",
      "Noise Cancelling": "Advanced",
      "Driver": "30mm"
    }
  }
];
